apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: display-state
spec:
  selector:
    matchLabels:
      app: frontend
  serviceName: display-service
  replicas: 2
  template:
    metadata:
      labels:
        app: frondend
    spec:
      containers:
      - name: display
        image: public.ecr.aws/y3z0f7y7/display
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: www
          mountPath: /app
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: display-service
spec:
  selector:
    app: frondend
  ports:
  - port: 8080
    targetPort: 8080

